### ISSUE TITLE
Support for refined types?

### ISSUE THREAD

**Issue by Hoffmannxd** [zio/zio-config#122]
Is desirable to have this feature?

**Comment by afsalthaj** [comment]
I think this will be useful feature to have.
As of now, we are relying on Magnolia to make deriving the descriptions
automatic. Let's have this issue open, for further discussions.

**Comment by leigh-perry** [comment]
I should be able to find time for this one.

**Comment by afsalthaj** [comment]
Thanks @leigh-perry for taking it up.
