### ISSUE TITLE
Support for standard configuration format

### ISSUE THREAD

**Issue by paulpdaniels** [zio/zio-config#123]
One piece that is missing for us to look into adopting this library is support for the typesafe configuration [format](https://github.com/lightbend/config#standard-behavior). It was alluded to in the doc pages (that more formats were coming) but that format would be high priority for us.

**Comment by afsalthaj** [comment]
We will definitely have integration with typesafe config formats, as well as reading hoccons !

**Comment by afsalthaj** [comment]
This is being tracked here:
https://github.com/zio/zio-config/issues/129

**Comment by afsalthaj** [comment]
Typesafe integration is merged.
