### ISSUE TITLE
Convert PropertyTree to Json/Hoccon/Key-value

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#130]
@jdegoes As of now `write` function returns a PropertyTree.
By write, I think, what we need is `write(config, value).asHoccon` or `write(config, value).asJson` and `write(config, value).asMap`, of which the last one already exists. Does this issue sound reasonable?

**Comment by afsalthaj** [comment]
KeyValue is already implemented using `flattenString`

**Comment by afsalthaj** [comment]
Json and Hoccon can be made available in type safe module

**Comment by jdegoes** [comment]
Agreed, although I'd do `to` instead of `as` because `as` implies "view" but immutable data is more like "conversion".

We can add these as syntax via the separate modules...

**Comment by pme123** [comment]
I think HOCON only can write a JSON. 

Here is an output example:
```
{
    # hardcoded value
    "db-con-ref" : {
        # hardcoded value
        "name" : "odsDb",
        # hardcoded value
        "type" : "local-ref"
    },
    # hardcoded value
    "name" : "postcodeLookup",
    # hardcoded value
    "params" : {
        # hardcoded value
        "name" : "Schwändi"
    },
    # hardcoded value
    "statement" : "\nSELECT f_postcode FROM t_places\n    WHERE f_name == ?\n",
    # hardcoded value
    "type" : "db-lookup"
}
```
I used it here https://github.com/pme123/zio-comps-module

**Comment by afsalthaj** [comment]
We have this functionality now

import zio.config.typesafe._

toHocon
toJson
