### ISSUE TITLE
Convert ConfigDocs to Readable formats

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#131]
As of now, `generateDocs` and `generateDocsWithValue` returns `ConfigDocs`, a datastructure that sort of act as a manpage and report respectively. We need to pipe this to much more readable format.
1. Markdown
2. A simple json (EDIT: deprioritised) 
3. Help Page
4. Or a simple table.

In-fact, we need support for all of it..

**Comment by ignaciomosca** [comment]
Onto it

**Comment by afsalthaj** [comment]
@ignaciomosca Any updates on this?

**Comment by ignaciomosca** [comment]
No updates. I got blocked regarding how to serialize to json without depending on other libraries. Do you have any plans on what to use to serialize to json?

**Comment by afsalthaj** [comment]
@ignaciomosca , Let's reprioritise JSON representation of documentation if that's a blocker. We have other formats that we need, such as tables (probably this is already done in libraries like clear-config) and we surely need it. 

Let me know if you would like to work other formats listed above.

**Comment by afsalthaj** [comment]
I also don't think we need any external dependencies to write a `https://github.com/zio/zio-config/blob/master/core/src/main/scala/zio/config/ConfigDocs.scala` .
There must be some way to track states to see the list of descriptions associated and the documentation tabs.
 So probably you can either use ZIO.Ref although it may turn out to be an overkill, because we are end of the day producing a string, and there are no errors and side-effects to be handled. At the same time, it may not be too bad an idea to have that in ZIO context, because users might be doing a effect before and after most of the times , such as `flatMap(doc => ZIO.effect(writeDocToAFile))`

**Comment by afsalthaj** [comment]
@jdegoes Any inputs here?

**Comment by jdegoes** [comment]
I would create a very lightweight format to describe the basic structure of a rendered document, including tables, headers, lists and bold/emphasis. Then render to that, and add methods to convert to markdown strings, json strings (no libs), plaintext, html, etc

**Comment by afsalthaj** [comment]
Awesome, sure it makes sense.

**Comment by afsalthaj** [comment]
I am working on this now
