### ISSUE TITLE
Support for opaque types

### ISSUE THREAD

**Issue by andreoss** [zio/zio-config#1391]
Can `DeriveConfig` work with opaque types? 

```scala
opaque type Template = String

object Template:
  import zio.*
  import zio.config.magnolia.*

  private def compile(v: String): Template = ???
  def apply(v: String): Template           = compile(v)

  given DeriveConfig[Template] = DeriveConfig[String].map(Template(_)) // Infinite loop here


```

**Comment by 987Nabil** [comment]
It is a loop, since `given DeriveConfig[Template]` is actually `given DeriveConfig[String]`
You need to write `given DeriveConfig[Template] = Config.string.map(Template(_))`
Or `given (using ev:Config[String]): DeriveConfig[Template] = ev.map(Template(_))`
