### ISSUE TITLE
Change doc operator to `??`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-config#142]
The doc operator is `?`, I suggest changing to `??` to make it less common and compatible with ZIO Test, which uses `??` for adding annotations to assertions.

**Comment by leigh-perry** [comment]
Implemented https://github.com/zio/zio-config/pull/145

**Comment by afsalthaj** [comment]
@leigh-perry approved and merged. Thanks @jdegoes for raising this issue.

**Comment by leigh-perry** [comment]
Merged
