### ISSUE TITLE
Reorganize top-level directory naming to be consistent with ZIO

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-config#147]
Because this project is ZIO Config, the top-level project names could be shortened / simplified to match ZIO conventions, e.g.:

 - `zio-config` => `core`
 - `zio-config-refined` => `refined`
 - etc.

**Comment by afsalthaj** [comment]
Will do this

**Comment by afsalthaj** [comment]
In here, https://github.com/zio/zio-config/pull/150
