### ISSUE TITLE
Support annotations for Magnolia-based deriving

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-config#166]
Could support a `@describe` annotation applied to terms in a product (fields in a case class), terms in a sum (subtypes of a sealed trait), and both products (case class annotation) and sums (sealed trait annotation). Currently descriptions can only be attached programmatically with the value-based DSL, this would allow them to be used with Magnolia-based deriving.

**Comment by afsalthaj** [comment]
This can be done fairly quickly as magnolia API does support it.


```scala
caseclass.parameters.map(t => t.typeclass.getConfigDescription(paths) ??? t.annotations...

```
Probably need to do certail low level cast operations such as `annotations.filterNot(_.isInstanceOf[scala.SerialVersionUID])`, or may be `filter(_.isInstanceOf[DescriptionAnnotation])`

**Comment by afsalthaj** [comment]
#185

**Comment by afsalthaj** [comment]
Closing this one as we fixed this issue
