### ISSUE TITLE
Convert FatalError to CustomError

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#177]
ReadError can happen across two phases. 
Let's example with an example:
It can happen when reading a file, or when trying to get a value given a key after the file is parsed. This becomes a valid scenario when it comes to handling Hoccon files.
Will it be ok to add `FatalError` as part of `ReadErrors` that may not be associated with a key.? Or should we lift everything to just `Throwable` and return a `Task`?

**Comment by jdegoes** [comment]
Probably best to return `Throwable` in cases where the error is truly unknown. You can make the custom errors extend that. Maybe some methods could stay specific...

**Comment by afsalthaj** [comment]
Ok, currently a couple of functions returns Throwable as the `E` in ZIO, and it may include a list of read errors as well, along with the possibility of some unknown error cases. I think we will keep it as it is.
