### ISSUE TITLE
Proposal: rename zio.config.Config to ZIOConfig

### ISSUE THREAD

**Issue by forficate** [zio/zio-config#190]
I am not too sure if this is too late being RC and a breaking change.

Renaming `Config` to `ZIOConfig` will help with import / namespacing ergonomics.

In my applications, I'll often have a case class named `Config` which means I would need to do something like` import zio.config.{Config => ZIOConfig}`, which is an extra step that wouldn't be required if we renamed zio.config.Config to something like ZIOConfig.

This is only an issue as `zio.config.Config` and an apps own `Config` class are generally used in the same place, so have scoping issues.

The simplest thing would be for an app not to use `Config` and use something like `AppConfig`, but it would be nice not to force that if it isn't too late to make the breaking change renaming to `ZIOConfig` or similar.

**Comment by afsalthaj** [comment]
@forficate we can still have breaking changes. We are not late.  RC and

**Comment by jdegoes** [comment]
`ZConfig` perhaps

**Comment by afsalthaj** [comment]
We should look at this issue now, before we release 1.0
