### ISSUE TITLE
ConfigDocs.Details.descriptions returns List[String] making it hard to generate nice messaging

### ISSUE THREAD

**Issue by forficate** [zio/zio-config#195]
When inspecting "ConfigDocs" to generate some configuration help text when you call `Details.descriptions` you get a `List[String]` back, which looks like `List(<empty>, value of type string)`.

The `<empty>` string looks to be the `ConfigSource` the value may be sourced from if set and `value of type string` the `ConfigDescriptor.description`.

It would be useful instead of returning `List[String]` instead returning a List of values where you can distinguish the type i.e `List(Source("<empty">), Descriptor("value of type string))`. This change would allow more flexibility generating help messages, i.e. if only using environment variables, you may just want to print `KEY: ConfigDescriptor.description` with some flag in the output if required or not.

**Comment by afsalthaj** [comment]
@forficate 
I think this distinguision is already in master, but not yet released?
https://github.com/zio/zio-config/blob/master/core/src/main/scala/zio/config/ConfigDocs.scala#L15 ?

Let me know if this is the suggestion

**Comment by afsalthaj** [comment]
@forficate This is already done and is released
