### ISSUE TITLE
Use `::` instead of List for List of Read Error

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#20]
`type ReadErrors = ::[ReadError]` in the package object

User `ReadErrors` instead of `List[ReadError]`
Ensures non empty list representing errors.

**Comment by leigh-perry** [comment]
Implemented https://github.com/zio/zio-config/pull/35

**Comment by leigh-perry** [comment]
I have implemented `NonEmptyList` as a reusable component:

```
  type NonEmptyList[A] = ::[A]

  object NonEmptyList {
    def apply[A](a: A, tail: A*): NonEmptyList[A] =
      ::(a, tail.toList)

    def concat[A](lerr: NonEmptyList[A], rerr: NonEmptyList[A]): NonEmptyList[A] =
      ::(lerr.head, lerr.tail ++ rerr)
  }
```
and defined `ReadErrors` as a synonym.
```
  type ReadErrors = NonEmptyList[ReadError]
  val ReadErrors: NonEmptyList.type = NonEmptyList
```

The idea being that we might need NEL again some time.

Comments on this are welcome.

**Comment by leigh-perry** [comment]
On discussion with @afsalthaj, we decided to avoid the NEL and hardcode it for `ReadErrors`
