### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Maatary** [zio/zio-config#202]
Hi, 

First, could you please let me know where can i ask question about the library ? is it here or you have a dedicated channel ? 

Second, my actually question, Is Zio Config, meant to replace/compete with circe ? Would it be possible at some point to use it as a json massaging library as we do with circe ?

**Comment by afsalthaj** [comment]
Hi,

> First, could you please let me know where can i ask question about the library ? is it here or you have a dedicated channel ?

> Second, my actually question, Is Zio Config, meant to replace/compete with circe ? Would it be possible at some point to use it as a json massaging library as we do with circe ?

@Maatary  I can see a question being closed 4 hrs ago. However, I believe I should answer it. Thanks for raising this question. It was actually a good one.

1) There is a dedicated channel for zio-config, where you can see active discussions
https://discordapp.com/channels/629491597070827530/633028431000502273
The same link is provided in the README of the library, which opens the door to whole zio-ecosystem and the corresponding channels. You will love it.

2) No, this is not a replacement for circe. This library doesn't aim to replace a library like circe, nor any json encoding and decoding, and its auto-derivations. 
I don't think any config management library such as type-safe, zio-config (which is now integrated with type-safe) or pure-config, or clear-config, or Cedi-config and a few bunch of them can replace json parsing libraries. Its different.

3) This is a library being built, aiming at solving config management problems (reading, mixing configs, mixing different sources of config, documenting them, writing it back to another source) in a purely functional way but not at the cost of leaking its complexity to user such as implicit derivations, or macros, or typeclasses. For the same reason, zio-config allows more composable operations, with out needing to know any more concepts than the simple functions in the library. It still have magical implicit derivations as a separate module, if that's your taste.

4) That said, some of the use-cases which you may rely on JSON encode-decode can actually be replaced with libraries that can just read and write a hocon given a case class. As far as zio-config is concerned, this capability is one of its features  which is still experimental in its nature.

For example, say you think you need a config file to read from s3 directory, which you load to application, run some computation, and updates the config back to s3, based on the result of computation. Assume that you need the content to look like json (or human optimised version called hocon), then zio-config can help you, with simple read and write functions.

Have a look at the design principles https://zio.github.io/zio-config/docs/design/design_index , if you need more info.
