### ISSUE TITLE
Typesafe config enhancement

### ISSUE THREAD

**Issue by devsprint** [zio/zio-config#208]
Most of the projects that are relying on Typesafe config library are using the default loader:
`ConfigFactory.load()`. 

Having the factory method in TypesafeConfig it will help and simplify the adoption of zio-config in existing projects.

**Comment by afsalthaj** [comment]
@devsprint  Thanks

In fact, type safe module is in its experimentation stage, and as soon as we have 1.0 release, we will have to cover more details of type safe by then. Hence, always good to get these type of PRs. Thanks!

**Comment by jdegoes** [comment]
Fixed in #208
