### ISSUE TITLE
Support other common data types

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-config#240]
- `UUID`
 - `Duration` / `FiniteDuration` (ZIO)
 - `LocalDate`
 - `LocalDateTime`
 - `LocalTime`
 - `Instant`
 - `URL`
 - `Boolean` (supporting things like `true` / `1` / `on`, and `false` / `0` / `off`)
 - `File`
 - `Path`
 - `BigInteger`
 - `BigDecimal`
 - All primitives (`Short`, `Byte`, etc.)
 - Tuples
 - Sets

Any others?

**Comment by marekklis** [comment]
PR for `UUID` https://github.com/zio/zio-config/pull/268

**Comment by marekklis** [comment]
I'll work on `Set` support

**Comment by afsalthaj** [comment]
This is done.
