### ISSUE TITLE
Add tests for Config.fromSystemEnv and Config.fromSystemProperties

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#243]
We have tests for ConfigSource.fromMap, which  `Config.fromSystemEnv` and `Config.fromSystemProperties` internally uses. 

We need some tests specific to sys.env, and sys.properties

**Comment by marekklis** [comment]
I'll do it

**Comment by afsalthaj** [comment]
Thanks @marekklis

**Comment by marekklis** [comment]
@afsalthaj https://github.com/zio/zio-config/pull/267 tests only `Config.fromSystemProperties` so we still need test for `Config.fromSystemEnv`
BTW `Config.fromSystemEnv` test is not easy to write because `sys.env` is an immutable Map.

**Comment by afsalthaj** [comment]
@marekklis sure. I remember zio provides some mock. Could you research on it?

**Comment by marekklis** [comment]
yes, I can take a look.

**Comment by afsalthaj** [comment]
@marekklis  Any luck on this?

**Comment by afsalthaj** [comment]
Can't see any major issues with loading system env or system properties, but these tests are good to have.
If no-one is actively working on it, lets close it for the time being.

**Comment by marekklis** [comment]
@afsalthaj There was discussion about this on discord channel some time ago and the conclusion was that ZIO config needs to be rewritten and not use `sys.env` method
https://discord.com/channels/629491597070827530/633028431000502273/697800157022126160
