### ISSUE TITLE
Move all of the magnolia-typesafe examples to tests

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#256]
This can reside in either magnolia module or type safe module.
Let's choose typesafe module, and have it dependent on magnolia.

**Comment by cecol** [comment]
I am looking at this.    
Is this purpose to move `https://github.com/zio/zio-config/tree/master/examples/src/main/scala/zio/config/examples/magnolia` and `https://github.com/zio/zio-config/tree/master/examples/src/main/scala/zio/config/examples/typesafe` to `https://github.com/zio/zio-config/tree/master/typesafe/src/test/scala/zio/config/typesafe` ?
