### ISSUE TITLE
No ConfigDocs.List node.

### ISSUE THREAD

**Issue by senia-psm** [zio/zio-config#257]
There is no such node as `ConfigDocs.List` to describe list of elements.
There is also no `ConfigDocs.Map` node to describe generic `Map`.

**Comment by afsalthaj** [comment]
Map isn’t implemented yet

**Comment by senia-psm** [comment]
@afsalthaj Map isn’t implemented^ but what about List?

**Comment by afsalthaj** [comment]
That was `close-and-comment` issue!
The issue is open.
