### ISSUE TITLE
Move the methods from config package to the companion object Config

### ISSUE THREAD

**Issue by wi101** [zio/zio-config#28]
Move: `int`, `double`, `string`,`long`, `short`,`uri`, `read`, `write`, and `report` to the companion object `Config` and make sure the examples still work.

**Comment by pgabara** [comment]
Hi Guys, it looks like a good first issue :) Can I take it?

**Comment by afsalthaj** [comment]
@pgabara  Sounds good. You could assign it to yourself, and then you could start doing it.
@wi101 If I am correct we are aiming for `import zio.config._, Config._` to access the above methods you mentioned and the `read`, `write`, and `report`?

**Comment by wi101** [comment]
@afsalthaj Yes, will update the descripion :-)

**Comment by pgabara** [comment]
@afsalthaj thanks! I could not assign it, probably I do not have enough permissions.
