### ISSUE TITLE
Add semantics of list and map in website

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#289]

**Comment by marekklis** [comment]
@afsalthaj Is this issue about updating this page: https://zio.github.io/zio-config/docs/configdescriptor/configdescriptor_index ?
There is a [chapter](https://zio.github.io/zio-config/docs/configdescriptor/configdescriptor_index#handling-list-is-just-easy) about making list already

**Comment by afsalthaj** [comment]
@marekklis yes. We need to expand the current explanation.

**Comment by afsalthaj** [comment]
List and map is pretty simple now. Removed over complications with a couple of PRs.
Closing this issue
