### ISSUE TITLE
Adjust comments to match syntax/combinators used in example (Move from <*> to |@|)

### ISSUE THREAD

**Issue by JonasAckermann** [zio/zio-config#29]
https://github.com/zio/zio-config/blob/6bb56fd6e57104f440684ca325737ad78752c044/src/main/scala/zio/config/examples/ReadWriteReport.scala#L8

None of the mentioned combinators appear in the following code exactly as shown, leading to potential confusion.

**Comment by wi101** [comment]
Thanks! 
we can implement ‘|’ and ‘|@| using the existing methods (or and xmap I think) and adjust the example

**Comment by afsalthaj** [comment]
We will be replacing <+> with |@|.

**Comment by JonasAckermann** [comment]
Will try my hand at this later, if it's ok :-)

**Comment by JonasAckermann** [comment]
Will wait for #37 to be merged before.

**Comment by afsalthaj** [comment]
@JonasAckermann Could you rename <*> to |@|.
I have reverted those change in my PR, coz that PR is actually intended for implementing only `Optional`

**Comment by wi101** [comment]
fixed at #55
