### ISSUE TITLE
Modularise zio-config, and separate type parameters into module

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#299]
```scala


trait ConfigModule {
  type KeyType
  type ValueType

  trait ConfigDescriptor[A]

}

trait StringConfigModule extends ConfigModule {
  type KeyType = String
  type ValueType = String

  val bigDecimal: ConfigDescriptor[BigDecimal] = ???


  def bigDecimal(path: String): ConfigDescriptor[BigDecimal] = ???

  val bigInt: ConfigDescriptor[BigInt] = ???

  def bigInt(path: String): ConfigDescriptor[BigInt] = ???

  val boolean: ConfigDescriptor[Boolean] = ???

  def boolean(path: String): ConfigDescriptor[Boolean] = ???

  val byte: ConfigDescriptor[Byte] =
    ???

  def byte(path: String): ConfigDescriptor[Byte] = ???
}

object string extends StringConfigModule

```

Any data types or functions that depend on the key type or value type will be mixed into config module. All of the types that requires `key` and `value` as string will be going to string module

**Comment by cecol** [comment]
I am looking at this. There is a conflict of `zio.config.ConfigDescriptor` and the one in above example: `ConfigModule.ConfigDescriptor`. Is `ConfigModule.ConfigDescriptor` would replace `zio.config.ConfigDescriptor` one?

**Comment by afsalthaj** [comment]
It does replace however every logic remains the same. We modularise things to not expose the types to users. It will be looking great for users. il soon raise a PR. Looking forward for your inputs there

**Comment by afsalthaj** [comment]
With #308 we fixed this issue.
