### ISSUE TITLE
Improve microsite

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#32]
1) Better layout. 
2) More accessibility to the contents with in each page.
3) Better home page (probably with images)

**Comment by afsalthaj** [comment]
@wi101 
It's going to be a big task, and we need to call and discuss the standards of the microsite.
Need help here.

**Comment by wi101** [comment]
I agree, it would be interesting :)

**Comment by afsalthaj** [comment]
This is in progress in branch magnolia. However we need to update for zio-config-refined and zio-config-magnolia

**Comment by afsalthaj** [comment]
This is being addressed as part of #148. Hence closing this one
