### ISSUE TITLE
Is it possible to maintain a 2.11 version of the lib ?

### ISSUE THREAD

**Issue by ubourdon** [zio/zio-config#324]

**Comment by afsalthaj** [comment]
We need to explicitly avoid magnolia module for 2.11 and let me if see that's possible. There were a few hiccups with respect to CI. It's an important issue, thanks for raising

**Comment by ubourdon** [comment]
So i quit zio config for the moment.
Waiting a 2.11 support or have time to upgrade my project to 2.12 scala version.
