### ISSUE TITLE
Make ConfigSource.SystemEnv fail when given an invalid delimiter (Ex: '.')

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#353]
One of the ways in which nesting is made possible with flattened key value pairs of system environment, is by passing a `keyDelimiter`. That way zio-config will retrieve them as a tree based on the hierarchy produced by the delimiter. 

However not all delimiters are valid in actual system environment. Example of such a delimiter is dot ('.'), meaning it won't make sense to use `export DB.PASSWORD="xyz"` generally. We have to `ZIO.fail` if user passed an invalid delimiter. A compile time safety would be much better if that's a maintainable solution. Meaning, good to find a solution other than `if keyDelimiter is in (invalidDelimiters) ZIO.fail`

**Comment by maciejbak85** [comment]
I can work on it

**Comment by afsalthaj** [comment]
@maciejbak85  thanks :)
