### ISSUE TITLE
Add support for more than 9 parameters in ProductBuilder

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#36]
In ProductBuilder.scala, currently we support only 9 parameters in the config.
We need to extend the boiler plate to support maximum number of variables.
It is fairly straight forward to add them, but it will be manual addition.

**Comment by leigh-perry** [comment]
This is implemented. Resolving scalafmt issue `[error] Search state exploded around line 251: /Users/s117476/dev/lp/zio-config/zio-config/src/main/scala/zio/config/ProductBuilder.scala`

**Comment by leigh-perry** [comment]
Manually formatted ProduceBuilder.scala then excluded it from scalafmt

**Comment by leigh-perry** [comment]
https://github.com/zio/zio-config/pull/52

**Comment by leigh-perry** [comment]
Included in https://github.com/zio/zio-config/pull/54 as part of conflict resolution
