### ISSUE TITLE
Support loading configuration from YAML

### ISSUE THREAD

**Issue by iravid** [zio/zio-config#375]
Load YAML using snakeyaml-engine, similar to how HOCON is loaded with Typesafe Config.

**Comment by iravid** [comment]
I'm working on this.

**Comment by afsalthaj** [comment]
Thanks @iravid 
That’s really cool

**Comment by afsalthaj** [comment]
@iravid Discard this message if you have rebased with master today.  
There were a few simplifications on error ADT merged to master last day, allowing writing simpler tests if we are adding new features.

**Comment by afsalthaj** [comment]
Done!
