### ISSUE TITLE
Replace WriteError with String and change ReadErrors.scala

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#38]
Rename `Errors.scala` file to `ReadErrors.scala` file;
Remove WriteError. Replace with String in places where WriteError is used.

We will change the encoding of ReadError to the following

```scala
sealed trait ReadError {
  def key: String
}

object ReadError {
 final case class MissingValue(key: String) extends ReadError(key)
 final case class ParseError(key: String, provided: String, `type`: String) extends ReadError(key)
}

```

This will make it consistent with zio

**Comment by pgabara** [comment]
Should we wait with this issue until #46 is closed?
