### ISSUE TITLE
Remove call to sys.env and use ZLayer

### ISSUE THREAD

**Issue by maciejbak85** [zio/zio-config#389]
According to discussion in PR: 
https://github.com/zio/zio-config/pull/388

would be good to make a change in ConfigSourceModule fromSystemEnv.
Change calling to external state `IO.effectTotal(sys.env)` and take env from a Layer.

This change will make this code more functional ( as no relying on external state ), and easier to unit test.
Currently in circleCI config there had to be set system variables, to make unit tests working.
So after using layer there, they can be removed from there.

**Comment by maciejbak85** [comment]
I would like to work on it ofc :)

**Comment by jdegoes** [comment]
@maciejbak85 I approve! Would be great to require that in the layer. Also for anything else where ZIO Config is touching the real world, would be better to grab that in the layer so it can be better tested.
