### ISSUE TITLE
Confusing error when creating a package object called config

### ISSUE THREAD

**Issue by vigoo** [zio/zio-config#403]
It feels natural to create our own package for defining our application's zio-config layer and naming it `config`, and following ZIO's module pattern, it often gets created as a _package object_.

This easily leads to the following error:

```scala
import zio.config._
import zio.ULayer

package object config {
  case class AppConfig()

  val live: ULayer[ZConfig[AppConfig]] = ???
}
```

```
type mismatch;
 found   : izumi.reflect.Tag[Nothing]
 required: zio.Tag[A]
    (which expands to)  izumi.reflect.Tag[A]
Note: Nothing <: A, but trait Tag is invariant in type A.
You may wish to define A as +A instead. (SLS 4.5)
```

which is not very user friendly, and is caused by importing the 

```scala
final def config[A](implicit tag: Tag[A]): ZIO[ZConfig[A], Nothing, A]
```
accessor function from `zio.config` that collides with the package object.

Renaming this to something less likely to collide with user code or scoping it to `ZConfig` or similar may reduce the possibility that people run into this.

**Comment by jdegoes** [comment]
Yes, we should avoid package names the same as method names.

**Comment by afsalthaj** [comment]
Let's rename the  `config`  to `getConfig`?
