### ISSUE TITLE
Bug (introduced lately) while writing back to json when the keys have dots in it

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#408]
This is towards the towards the edge of the app, where rendering the config as a json seem to be buggy when the key themselves has "." (dots) in it. This also seem to be a bug that was introduced lately (probably https://github.com/zio/zio-config/commit/3f1158fee04dab70e2b19af56215cbb9e49afb10#diff-7b2e631c24e9cbd8367ceb16e6ed03d6), and shows an absence of property based test. The fix seem to be relatively simple as it doesn't involve the core module (property tree, read, write logic etc).

For example:

```scala
  import zio.config.magnolia.DeriveConfigDescriptor.descriptor
  
  case class CaseClass(map: Map[String, String])
  val x = CaseClass(Map("a"  -> "y"))
  println(write(descriptor[CaseClass], s).map(_.toJson))

```

produces the correct result which is:

```scala
Right({
    "map" : {
        "a" : "y"
    }
})
```

However, when the keys have dots in it,

```scala
  case class CaseClass(map: Map[String, String])
  
  val x = CaseClass(Map("a.b"  -> "y"))
  
  println(write(descriptor[CaseClass], s).map(_.toJson))

```
yielding

```scala

Right({
    "map" : {
        "a.b  " : {
            "a" : {
                "b" : "y"
            }
        }
    }
})

```

The expected result is 

```scala
Right({
    "map" : {
        "a.b" : "y"
    }
})
```

## It is simple to fix.
Keep a note that the bug is not at the `PropertyTree` side, as it produces the correct result. It is during rendering back to Json (HOCON)

```

  println(write(descriptor[CaseClass], x))

```

gives

```scala
  Right(Record(Map(map -> Record(Map(a.b -> Leaf(y))))))
```

Hence the fix should be relatively simple.

**Comment by shankarshastri** [comment]
I was trying to take a look found this one:
https://github.com/lightbend/config/issues/493

**Comment by afsalthaj** [comment]
@shankarshastri yes but it seems we are able to read the config properly. It’s, I guess, a small
bug in the write module.

**Comment by shankarshastri** [comment]
@afsalthaj , if you can give me a few pointers I can pick this and continue on the same.

**Comment by afsalthaj** [comment]
@shankarshastri  Let me try and understand what went wrong

**Comment by afsalthaj** [comment]
@shankarshastri  

The reason is, we have to carefully / explicitly quote the path when calling typesafe config library's (low level) APIs.

In TreeToHoconSupport.scala
// Replacing ConfigFactory.empty().withValue(last, ConfigValueFactory.fromAnyRef(tree.value))
ConfigFactory.empty().withValue(s""" "${last}" """, ConfigValueFactory.fromAnyRef(tree.value))

can solve the issue.

Would you be happy doing this, backed by a property based test?

The right thing to do is shift the following unit test with a complex hocon string to a property based testing. This is in TypesfafeConfigReadWriteTest.scala

```scala
 test(
          "complex source: read(descriptor from typesafeSource) == read(descriptor from write(descriptor, read(descriptor from typesafeSource)))"
        )
```

We can give a release for zio-config in 1-2 days if we could get this into master. Happy to give more inputs if needed.

**Comment by shankarshastri** [comment]
Sure, @afsalthaj , I can start with it. With respect to src changes, I understood from the above, to explicitly make `last` to the string.
I had doubts about w.r.t property testing. I was exploring the zio-test for the same but was not sure how to generate an input for the test using the same.

**Comment by afsalthaj** [comment]
@shankarshastri Sure. Let’s create a separate issue for property based testing and we both can work on that. 

How about creating the src change mentioned and raise a pull request to fix this issue?

**Comment by shankarshastri** [comment]
@afsalthaj , I have added the small fix as part of this PR:
https://github.com/zio/zio-config/pull/416/files
