### ISSUE TITLE
Refactor module design

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-config#46]
Right now we use ZIO Environment for `ConfigSource`, but I think we should refactor that a bit, and use ZIO Environment directly for accessing configuration.

The most natural name to use for the module would be `Config`, probably, which would mean changing the existing `Config` to `ConfigDescriptor` or `ConfigFormat` or something similar.

Then we could construct a module like this:

```scala
trait Config[A] {
  def config: Config.Service[Any, A]
}
object Config {
  trait Service[A] {
    def config: UIO[A]
  }
}
object config {
  def config[A]: ZIO[Config, Nothing, A] = ZIO.accessM(_.config)
}
```

Now users could access config in their application like this:

```scala
import zio.config._ 

...
case class MyConfig(port: Int, server: String)
...
for {
  myConfig <- config[MyConfig]
} yield (myConfig.port, myConfig.server)
```

This leaves what to do with `ConfigSource`. I think it could become not a module, but a trait or even just a function, that can load configuration. Then we can have:

```scala
object Config {
  ...
  def make[A](source: ConfigSource, configDescriptor: ConfigDescriptor[A]): IO[ReadError, Config[A]] = ???
  ...
}
```

which effectfully builds a `Config` module given a way to read it. Or perhaps that's too fancy and we should just put `fromMap`, fromEnv`, etc., methods directly on `Config`?

**Comment by leigh-perry** [comment]
@jdegoes  If I interpret this idea correctly, due to referential transparency `MyConfig` would be re-evaluated each time `config[MyConfig]` is summoned?

**Comment by afsalthaj** [comment]
@jdegoes 
Thanks for that. It sounds  good to have the MyConfig as part of the Environment rather than the ConfigSource

To avoid the re-evaluation, lets say

```scala
trait Config[A] {
  def config: A
}

object config {
  def config[A]: ZIO[Config, Nothing, A] = ZIO.accessM(_.config)
}

object Config {
  ...
  def make[A](source: ConfigSource, configDescriptor: ConfigDescriptor[A]): UIO[Config[A]] = {
      read(configDescriptor).provide(source)
  }
  ...
}

```

And at the user site:
```scala
 import zio.config._

val myApp: ZIO[Config, Nothing, A] =  
 for {
     myConfig <- config[MyConfig]
  } yield (myConfig.port, myConfig.server)

```

and in the main app:

```scala
val configDescription: ConfigDescriptor[MyConfig] = 
   (int("PORT") |@| string("SERVER"))(MyConfig.apply, MyConfig.unapply)


fromEnv(configDescription).flatMap(myConfig => myApp.provide(myConfig))

```

**Comment by leigh-perry** [comment]
This is part of a real-world app pattern where you want to do some relatively heavyweight setup only once as part of a _bootstrap_ phase, as shown in @afsalthaj 's comment. For example, reading config, creating a Spark session, etc.

You need to be aware that referential transparency can cause constant re-evaluation, so the bootstrap phase is to _resolve_ the program, providing it with those once-only environmental dependencies.

I have a [sample app template](https://github.com/leigh-perry/template-cats-zio-app/blob/master/apps/lptemplateprojectname/src/main/scala/com/lptemplatecompany/lptemplatedivision/lptemplateservicename/AppMain.scala) that prototypes this.

**Comment by jdegoes** [comment]
@jdegoes If I interpret this idea correctly, due to referential transparency MyConfig would be re-evaluated each time config[MyConfig] is summoned? (For example, re-reading a json or hocon file etc)

Yes, but in most common cases, `config` will be defined in terms of `ZIO.succeed`.

The actual _loading_ of the data occurs in the effect returned by `Config.make`, which will typically occur during startup as the dependencies are wired together.

So it will not be necessary for a user to concern themselves with this; from their perspective, the config data is a constant across their entire application.

Now, the interface _allows_ one to provide a config module backed by "live" data, so it could change; but the default implementation would not do that. In fact, one could make that mandatory by making `config: A`, although it's not strictly necessary for the above reasons.

**Comment by afsalthaj** [comment]
@jdegoes that’s nice.

To reinforce my understanding,
Config.make is nothing but

read(description).provide(env).map(result => new Config{ override def Config = Zio.succeed(result)}


And user calls at this only in the main. 
This means accessing MyConfig by the user anywhere from the environment is accessing a constant value. Isn’t it?

**Comment by afsalthaj** [comment]
https://github.com/zio/zio-config/pull/50

**Comment by jdegoes** [comment]
Yes that's right, and you can see it will not be reloaded every time you access it.

**Comment by afsalthaj** [comment]
This was implemented (exactly the same pattern) in #72

**Comment by afsalthaj** [comment]
Reopening, since we can keep this for another round of review during direct-discussion.

**Comment by afsalthaj** [comment]
This is done!
