### ISSUE TITLE
Provide a convenient way to read config from resource

### ISSUE THREAD

**Issue by snowsilver** [zio/zio-config#501]
@afsalthaj Thank you for the videos about zio-config on Youtube. I'm trying to use zio-config and found that there is no method to read config from resource path directly. Instead I found methods to read config from `Path`, `File`, `String`

Of source, we can read resource and then convert to string or file but It would be convenient to read config from resource directly.

What do you think?

**Comment by afsalthaj** [comment]
@snowsilver  Thanks for asking this here. Couldn't we use `TypesafeConfig. fromDefaultLoader` or `TypsafeConfigSource. unsafeDefaultLoader` ?

You need zio-config-typesafe module in your build. See if this helps.

**Comment by afsalthaj** [comment]
@snowsilver  Meanwhile, sorry for the delay. For some reason, I completely missed out this issue.

**Comment by snowsilver** [comment]
@afsalthaj Thank you for the comment. :-) zio-config supports various types of config such as yaml, hocon, properties. Basically, config can be loaded from separated file from file system or classpath in the jar file. I suggested that adding  a common way to load config by locations of config file for all config types and I wonder that feature is helpful for the other users. 

and I wonder that do you have a plan to provide a similar feature as spring profile out of box?

**Comment by snowsilver** [comment]
> Thanks for asking this here. Couldn't we use TypesafeConfig. fromDefaultLoader or TypsafeConfigSource. unsafeDefaultLoader ?

I just checked Typesafe config's behaviour. It seems Typesafe config already supports profile and loading directly from resource. I missed that because I tried only zio-config-yaml. :sweat_smile:  I found there are all features that I want in zio-typesafe-config if I change file format of config.
thank you
