### ISSUE TITLE
 zio-config-magnolia 1.0.3 didn't get published

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-config#510]
It's not on Maven
https://repo1.maven.org/maven2/dev/zio/zio-config-magnolia_2.13/

And it's not mentioned in the logs
https://github.com/zio/zio-config/runs/2297366374?check_suite_focus=true

**Comment by sideeffffect** [comment]
The issue might be that Magnolia is not a 2.11 project and the sbt project `root` contains only 2.11 projects?

**Comment by mijicd** [comment]
Not only magnolia, i think the same issue is for 2 more projects (as you described).

I already informed @afsalthaj about this, so i propose to kerge your fix, ans eelease 1.0.4 asap.

**Comment by mijicd** [comment]
*Update:*  scratch my message above, the hotfix obviously doesn't work.

**Comment by sideeffffect** [comment]
Yeah, there are further issues: https://github.com/zio/zio-config/pull/514

**Comment by sideeffffect** [comment]
I think we've fixed this! :tada:

**Comment by mijicd** [comment]
Closed in #514
