### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by YuMuuu** [zio/zio-config#568]
https://github.com/zio/zio-config/blob/926fe4a3677ee301411192934e11d38fe0aeab78/README.md#L23

`examples/src/main/scala/zio/config/examples` is cant junp in  mster branch.

I heard rumors that a very good library 👀

**Comment by afsalthaj** [comment]
https://github.com/zio/zio-config/pull/565

**Comment by afsalthaj** [comment]
Closing this issue as we merged #565

**Comment by YuMuuu** [comment]
thanks
