### ISSUE TITLE
Add Empty Config

### ISSUE THREAD

**Issue by wi101** [zio/zio-config#57]
Remove `Pure` Config and add `Empty` Config which describes an empty configuration and preserve the type of the config

```scala
final case class Empty[A]() extends Config
```

**Comment by afsalthaj** [comment]
case class Empty[A](), interpreting it during Read can be a bit tricky.
Let's discuss.

**Comment by afsalthaj** [comment]
#58

**Comment by afsalthaj** [comment]
@wi101  i think we merged this. Hence closing this :)
