### ISSUE TITLE
Remove the use of hardcoded newline in `ConfigReport`

### ISSUE THREAD

**Issue by Michaelt293** [zio/zio-config#69]
Currently, the config report is converted to string as follows-

```
  override def toString: String =
    list.mkString("\n")
```

The use of a hardcoded newline will cause problems for Windows users. There are a couple of approaches I think we can take -

1. Still override `toString` but use ", " instead  and provide a separate method for using newlines.
2. Do not override `toString` and provide a separate method for using newlines.
3. Still override `toString` but use `System.lineSeparator()` instead of `"\n"`.

I believe that the third option is against the philosophy of ZIO so I suggest either option one or two. Either way, I believe we need a separate method for using newlines.

**Comment by afsalthaj** [comment]
I think we don’t need toString implementation at all. We can just remove it
