### ISSUE TITLE
`println` in ConfigSourceModule.fromSystemEnv (3.0.0-RC1)

### ISSUE THREAD

**Issue by aborg0** [zio/zio-config#749]
At [line 574](https://github.com/zio/zio-config/blob/v3.0.0-RC1/core/shared/src/main/scala/zio/config/ConfigSourceModule.scala#L574) there is a `println` statement (`println("going to calculate tree")`), which is probably unintentional, was used for debugging. (Present also on [master](https://github.com/zio/zio-config/blob/master/core/shared/src/main/scala/zio/config/ConfigSourceModule.scala#L574).)

**Comment by afsalthaj** [comment]
Fixed in 3.0.0-RC3 and 2.0.3
