### ISSUE TITLE
Build set up for microsite.

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-config#75]

**Comment by afsalthaj** [comment]
Set up the sbt build for microsite. 
It should be be matching with zio core library.
Once the set up is done, we will decide what exactly to document.

**Comment by mijicd** [comment]
I recommend to take a look at `zio-nio`, as this is the setup you want to have. The core library is very similar, but the pages are set slightly differently.

**Comment by afsalthaj** [comment]
@mijcd I have followed zio-nio. 
Could you help publishing (if it’s about pushing to  a separate branch gh-pages etc) an initial version. #90

**Comment by mijicd** [comment]
@afsalthaj I'll take a look at it first thing in the morning!

**Comment by afsalthaj** [comment]
Thanks @mijcd. Sounds great :)
