### ISSUE TITLE
Has defect when accessing ConfigSource from environment

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio-config#785]
Hello there - when trying out zio-config 2.0.0 I experience a runtime error. Here's a test to reproduce:

```scala
import zio.config._
import zio.test._
import zio._

object MainSpec extends DefaultRunnableSpec {
  val spec = suite("MainSpec")(
    testM("Can layer config source") {
      val program = ZIO.service[ConfigSource].map(println(_)) *> assertCompletesM

      program.provideLayer(ConfigSource.fromMap(Map("Hello" -> "World")).toLayer)
    }
  )
}
```

It fails with

>java.lang.Error: Defect in zio.Has: Could not find package::ConfigSource inside Map(ConfigSourceModule::ConfigSource -> Reader(Set(ConfigSourceName(constant)),zio.ZManaged$$anon$2@1448a11c))

Interestingly, in my application the error message is the opposite, i.e. it cannot find `ConfigSourceModule::ConfigSource` because the key in the map is `package::ConfigSource` 🤔

**Comment by afsalthaj** [comment]
I have been travelling quite a bit during this time, and catching up with the issues. Let me take a look. Thanks for reporting.

**Comment by afsalthaj** [comment]
It seems to be an issue that's quite interesting, but not quite specific to zio-config though. Hence the issue will be long-living here.


Anyway, atleast for the time being , if you need really need to make `ConfigSource` a layer, we have some helpers that can come in handy

```scala
      final case class MyConfig(age: Int)

      val config  =
        ConfigSource.fromMap(Map("age" -> "20")).toLayer >>> configLayer(int("age").to[MyConfig])

       val app: ZIO[Has[MyConfig] with zio.console.Console,java.io.IOException, Unit] =
          getConfig[MyConfig].flatMap(cfg => putStrLn(cfg.toString))

      app.provideSomeLayer[Console](config) *> assertCompletesM
```

**Comment by regiskuckaertz** [comment]
Thanks mate, yes I thought the issue was not at the right place indeed.

**Comment by afsalthaj** [comment]
👍🏻

**Comment by amricko0b** [comment]
Greetings, @afsalthaj !

Could you please provide some more information about this issue's nature, if you know what's going on? Why ZIO tries to find object by wrong key in the environment? Are there some other issues that are somehow connected with this one?

I'm having the same issue and it would be very helpful to know more and to find out when the cause will be fixed.

Thanks in advance.
