### ISSUE TITLE
Combining ConfigSources

### ISSUE THREAD

**Issue by Michaelt293** [zio/zio-config#81]
`zio-confing` currently lacks functionality to compose config sources.  I believe it would be advantageous for users to be able to create new config sources by composition. This would allow, for example, a user to override a config setting from a file using a system property. 

A work in progress PR has been opened-
https://github.com/zio/zio-config/pull/80/files

**Comment by afsalthaj** [comment]
This sounds good. 
 Composing sources to form a structure that also represents the priority of sources.
