### ISSUE TITLE
Custom decoding not working

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-config#846]
Hi,

I have a sample minimal code to reproduce an issue I am facing

```scala
package CustomDecodedTypeConf {

  val hoconValue = """
  kafka = {
    topics = ["one", "two"]
    broker: "127.0.0.1:28000"
  }
  """

  case class Address(host: String, port: Int) {
    override def toString = s"$host:$port"
  }
  object Address {
    def parse(value: String): Either[String, Address] = value match {
      case s"$host:$port" if port.toIntOption.nonEmpty => Right(Address(host, port.toInt))
      case e                                           => Left(s"invalid address: $e")
    }
  }

  given ConfigDescriptor[Address] =
    Descriptor[String].transformOrFailLeft(Address.parse)(_.toString)

  case class Kafka(topics: List[String], broker: Address)

  val description: ConfigDescriptor[Kafka] = (Descriptor[Kafka])
  object App extends zio.ZIOAppDefault {
    val source = TypesafeConfigSource.fromHoconString(hoconValue)
    val desc   = nested("kafka")(description from source)
    override def run = {
      for {
        data <- read(desc)
        _    <- Console.printLine(data)
        _ = assert(data == Kafka(List("one", "two"), Address("127.0.0.1", 28000)))
      } yield ()
    }
  }
}
```

even though I have provided a given instance of `ConfigDescriptor[Address] `, it still seems that it is being ignored during auto derivation

**Comment by bilal-fazlani** [comment]
If I create a `Descriptor` manually, it works

```scala
given Descriptor[Address] =
    Descriptor.from[Address](Descriptor[String].transformOrFailLeft(Address.parse)(_.toString))
```

**Comment by afsalthaj** [comment]
@bilal-fazlani , Yes, the type class used for auto-derivation is `Descriptor` and not `ConfigDescriptor`. In fact, `ConfigDescriptor` is not a type class.

Wee can support something along the lines of auto-deriving `Descriptor` given a `ConfigDescriptor`, however not a preferred method. The preferred way is to define instance for `Descriptor`, and obviously avoid orphan instances as well. Example: Make sure address descriptor exist in the companion object of `Address`.

**Comment by bilal-fazlani** [comment]
I am only puzzled by how are the examples compiling? 🤔 

https://github.com/zio/zio-config/blob/master/examples/shared/src/main/scala/zio/config/examples/magnolia/AutoDerivationCustom.scala#L23-L28

When I copy that code to my local setup (Scala 3), it fails to compile. When I write `Descriptor[String]` I get a `ConfigDescriptor[String]` in return.   @afsalthaj

**Comment by afsalthaj** [comment]
It should be returning `Descriptor`.
https://github.com/zio/zio-config/blob/master/magnolia/shared/src/main/scala-2.12-2.13/zio/config/magnolia/Descriptor.scala#L293
