### ISSUE TITLE
Is the website outdated ?

### ISSUE THREAD

**Issue by yadavan88** [zio/zio-config#851]
Hey,
I am just starting with ZIO Config for the first time, and was just trying to do a simple one. But it seems the examples in the website doesn't work/compile. Could not find anything like |@| in the ConfigDescriptor as well. 
Is the website not updated or is there a different website for the new version?

**Comment by afsalthaj** [comment]
The website content is updated but we haven’t published them yet. You can see the content under the docs folder in the repository. 

We will be trying to fix this soon

**Comment by yadavan88** [comment]
Thanks for the quick reply. I will look at the docs. In the meantime, it would be nice to mention that the website is outdated in the main readme file and redirect to the docs for the people who are interested. I could just create a PR with 1-2 sentences in the main readMe for benefiting ppl like me.

**Comment by yadavan88** [comment]
Hey @afsalthaj I created a short PR just with some changes in readme and website to redirect to the docs path. Please consider if it makes sense.

**Comment by yadavan88** [comment]
Closing this since the PR is merged
