### ISSUE TITLE
Support for zio.Duration (or scala) as Native Type

### ISSUE THREAD

**Issue by ianlintner** [zio/zio-config#943]
As config user I find myself needing Duration for things timeouts. 

Duration would be nice sugar to support ZIO duration as "primitive" config type.

Up for discussion on why/why but I would be willing to create PR.

**Comment by ianlintner** [comment]
This may already be a thing looking at source/search.

**Comment by afsalthaj** [comment]
Let’s add them in if you could raise a PR:)
